### ISSUE TITLE
Imported project not found

### ISSUE THREAD

**Issue by hols-zhaw** [sgreben/FsTypeVis#1]
Hi, I'd really like to try this out because it promises exactly what I'd like to be able to do.

Unfortunately, VS2015 can't load the solution properly. The following error messages are displayed:

```
> C:\ ... \FsTypeVis-master\src\FsTypeVis\FsTypeVis.fsproj : error  : The imported project "C:\ ... \FsTypeVis-master\.paket\paket.targets" was not found. Make sure the path in the <Import>-declaration is correct and the file exists on the drive.  C:\ ... \FsTypeVis-master\src\FsTypeVis\FsTypeVis.fsproj
> 
> C:\ ... \FsTypeVis-master\src\FsTypeVis\FsTypeVis.Tests.fsproj : error  : The imported project "C:\ ... \FsTypeVis-master\.paket\paket.targets" was not found. Make sure the path in the <Import>-declaration is correct and the file exists on the drive.  C:\ ... \FsTypeVis-master\src\FsTypeVis\FsTypeVis.Tests.fsproj
```

I installed Paket and looked at the project files. The only thing I can spot is that the folder `.paket` doesn't exist. I don't know Paket so please bear with me.

Some instructions on how to compile and use in the readme would be awesome. Thank you!

**Comment by sgreben** [comment]
Hi, great to hear! It's been a while since I touched this code - I'll have a look to see if I can fix the build. 

In the meantime (if you need something that builds _now_), you can create a new VS F# project and simply add all the *.fs files from src/ to it. 

The file `Script.fsx` (also in src/) contains a usage example (with hardcoded paths local to my machine...). Here it is (with upper-case placeholders):

```
    let myVis = Visualisation.visualiseLayered typeof<TYPE TO VISUALISE> Visualisation.Palettes.whiteText
    Graphics.Rendering.Html.renderToFile "PATH TO WRITE HTML TO" (Seq.singleton myVis)
```

**Comment by hols-zhaw** [comment]
Thanks, I managed to add FsTypeVis as a project to my solution, compile it as a library and use it in the main project. It works just fine =) even though large domain models become somewhat cluttered. But at the moment it serves my needs perfectly as I can quickly visualize the model and discuss it with people!

Thank you very much for this.

**Comment by sgreben** [comment]
This is awesome, you're actually using this for a real project! I'm very glad to have made a useful thing. Is there anything in particular that you'd like to see improved? This is now fun to work on :)

By the way, I just pushed commits adding the missing Paket files - I don't have VS2015 to test with, but a fresh clone of this repo now builds on VS2013 at least.
